update: added logs for orchestrator
madara-alliance/madara-orchestrator pull request #142
Opened 2024-10-08 12:26 UTC by heemankv

2024-10-09 05:30 UTC, heemankv reviewed
Done with Self Review

2024-10-09 09:19 UTC, Mohiiit requested changes
I have less context on code so maybe you would be able to make a better decision on whether to use info or debug on some places.

2024-10-09 09:19 UTC, Mohiiit commented on crates/orchestrator/src/tests/common/mod.rs
>              Err(e) => eprintln!("Error deleting queue {}: {:?}", queue_url, e),
shall we have a warn or error tracing here?

2024-10-09 09:19 UTC, Mohiiit commented on crates/prover-services/sharp-service/src/client.rs
> +        tracing::debug!("Sharp Service: Sending PIE to SHARP");
```suggestion
        tracing::info!("Sharp Service: Sending PIE to SHARP");
```

2024-10-09 09:19 UTC, Mohiiit commented on crates/prover-services/sharp-service/src/client.rs
> +        tracing::info!("Sharp Service: Job status response: {:?}", res);
maybe add trace below where we have error or status okay? wdyt?

2024-10-09 09:19 UTC, Mohiiit commented on crates/prover-services/sharp-service/src/lib.rs
> +                tracing::error!("Sharp Service: Task is invalid: {:?}", invalid_reason.clone());
do we need clone here?

2024-10-09 09:19 UTC, Mohiiit commented on crates/settlement-clients/ethereum/src/lib.rs
> +        tracing::info!("Ethereum Settlement Client: Updated state with calldata {:?}", tx_receipt.transaction_hash);
message not relevant, need to update this

2024-10-09 09:19 UTC, Mohiiit commented on crates/settlement-clients/starknet/src/lib.rs
> +                    tracing::info!("Transaction {} is settled", tx_hash);
```suggestion
                    tracing::info!("Transaction {} is verified", tx_hash);
```

2024-10-09 09:19 UTC, Mohiiit commented on crates/settlement-clients/starknet/src/lib.rs
> +                    tracing::error!("Max retries exceeeded while waiting for tx {tx_hash} finality.");
```suggestion
                    tracing::error!("Max retries exceeeded while waiting for tx {:?} finality.", tx_hash);
```

2024-10-09 09:19 UTC, Mohiiit commented on crates/settlement-clients/starknet/src/lib.rs
> +                tracing::info!("Tx {tx_hash} has achieved finality");
```suggestion
                tracing::info!("Tx {:?} has achieved finality", tx_hash);
```

2024-10-10 05:57 UTC, apoorvsadana commented
Closing in favor of #147

2024-10-10 05:57 UTC, closed without merging